<ul class="qa-nav-main-list">
    <li class="qa-nav-main-item qa-nav-main-questions">
        <a href="index.php" class="qa-nav-main-link">Đặt câu hỏi</a>
    </li>
    <li class="qa-nav-main-item qa-nav-main-unanswered">
        <a href="index.php?controller=Pair&action=add" class="qa-nav-main-link">Quản lý câu hỏi-trả lời</a>
    </li>
    <li class="qa-nav-main-item qa-nav-main-unanswered">
        <a href="index.php?controller=PairFeedBack&action=list" class="qa-nav-main-link">Phản hồi người dùng</a>
    </li>
<!--    <li class="qa-nav-main-item qa-nav-main-tag">
        <a href="http://localhost:8888/q2a/index.php?qa=tags" class="qa-nav-main-link">Menu 3</a>
    </li>
    <li class="qa-nav-main-item qa-nav-main-user">
        <a href="http://localhost:8888/q2a/index.php?qa=users" class="qa-nav-main-link">Menu 4</a>
    </li>
    <li class="qa-nav-main-item qa-nav-main-ask">
        <a href="http://localhost:8888/q2a/index.php?qa=ask" class="qa-nav-main-link">Menu 5</a>
    </li>-->
</ul>
<div class="qa-nav-main-clear">
</div>