
<div class="qa-nav-main">
    <?php
    include 'include/top-navigation.phtml';
    ?>
</div>

<div class="qa-main-2">
    <h1><span style='display: inline-block'>Chi tiết câu hỏi-trả lời: </span><span style='float:right; display: inline-block'><a href='index.php?controller=Pair&action=list'>Xem tất cả</a></span></h1>
    <?php
        if (isset($data["pair"]))
        {
            
            $p = $data["pair"];
//            $p = new PairModel();
            echo "<h2>Câu hỏi:</h2>";
//            $p = new PairModel();
            echo $p->QUESTION;
            echo "<h2>Câu trả lời:</h2>";
            echo "<p><b>{$p->SOURCE_TITLE}</b></p>";
            echo "<p>{$p->ANSWER}</p>";
            
            echo "<h2><span style='display: inline-block; width: 150px'>Trạng thái</span> <span style='color:green'>{$p->STATUS}</span>";
            echo "<h2><span style='display: inline-block; width: 150px'>Điểm đánh giá</span> <span style='color:green'>{$p->SCORE}</span>";
            echo "<h2><span style='display: inline-block; width: 150px'>Ngày thêm</span> <span style='color:green'>{$p->DATE_ADDED}</span>";            
        }
    ?>
</div> <!-- END qa-main -->

